/-
Copyright (c) 2026 Thomas R. Murrills. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Thomas R. Murrills
-/
module

public import Lean.Elab.Command
public import ImportGraph.Shake.Basic

import Lean.Compiler.LCNF.Main
import Lean.Compiler.LCNF.ToDecl
import Lean.Compiler.NoncomputableAttr
import ImportGraph.Shake.EnvExtension
import ImportGraph.Lean.Syntax

import all Lean.Compiler.LCNF.Visibility -- for `collectUsedDecls`

/-!
# Declaration needs

This file records the needs of declarations in a "non-baked-in" manner via `DeclNeeds`.
We record in what manner one declaration needs another (e.g. in its type), and then postpone the
calculation of what import needs this implies. This sets us up to provide finer explanations.

We also define `ImportNeeds` so that we can express when an import is allowed to be meta (or not).

Note that, crucially, `DeclNeeds` is agnostic to the source of our import hierarchy, as it uses
module names instead of e.g. `ModuleIdx`s/`ModIdx`s. Hence these functions are compatible with both
a `WorkspaceModel` approach and an `Environment` approach.

This file culminates in `withElabCommandCapturingNeeds`, which elaborates a command and captures
the (transitive) `DeclNeeds` of declarations produced in that command, including e.g. the needs
implied by the command's syntax.

## Future Work

- Write up more thorough documentation when this settles down.
- Handle meta IR.
- Performance: many of the data structures here could be improved. There's a lot of
  pointer-chasing.
- Revamp indirect mod uses. Currently they are associated with the declaration indirectly requiring
  them and added to the decl import needs specially. Instead, we should split them out. Also, we
  currently spoof the `kind`.
- Split out extra mod uses into a special command needs. Also put the syntax needs there; these
  should not be decl needs.
- Handle autogenerated declarations more consistently.
- Give a closer look to things like `@[csimp]`.
-/

open Lean ImportGraph Shake

namespace ImportGraph.Shake

public section fromShake

/-!
## Shake declarations

This section (`fromShake`) is inlined verbatim from shake, modulo whitespace.

Copyright (c) 2023 Mario Carneiro. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Mario Carneiro, Sebastian Ullrich
-/

def isDeclMeta' (env : Environment) (declName : Name) : Bool :=
  -- Matchers are not compiled by themselves but inlined by the compiler, so there is no IR decl
  -- to be tagged as `meta`.
  -- TODO: It would be better to base the entire `meta` inference on the IR only and consider module
  -- references from any other context as compatible with both phases.
  let inferFor :=
    if declName.isStr &&
      (declName.getString!.startsWith "match_" || declName.getString! == "_unsafe_rec")
    then
      declName.getPrefix else declName
  -- `isMarkedMeta` knows about non-defs such as `meta structure`, isDeclMeta knows about decls
  -- implicitly marked meta
  isMarkedMeta env inferFor || isDeclMeta env inferFor

/--
Given an `Expr` reference, returns the declaration name that should be considered the reference, if
any, but from the environment directly.
-/
def Lean.Environment.getDepConstName? (ref : Name) (env : Environment) : Option Name := do
  -- Ignore references to reserved names, they can be re-generated in-place
  guard <| !isReservedName env ref
  -- `_simp_...` constants are similar, use base decl instead
  return if ref.isStr && ref.getString!.startsWith "_simp_" then
    ref.getPrefix
  else ref

end fromShake

public section

/-- A way in which a declaration might demand an imported module. Note that there may be multiple
demands on the same module from the same declaration, which thus may require multiple of these. -/
structure ImportNeedsKind extends NeedsKind where
  /-- A flag for the case where the ambient declaration needs a meta declaration from the needed
  module. In that case, the import is allowed to be meta, but does not have to be. Note that
  ordinary expression uses also `allowMeta`; it is only usage in the computational content (LCNF)
  that will *disallow* meta and set this to false.

  However, to allow `NeedsKinds` constructors to not conflict with `.allowMetaPub`, we set this to
  `isMeta` by default. -/
  allowMeta : Bool := isMeta
  /-- Needing a meta import implies `allowMeta = true`. -/
  allowMeta_if_isMeta : !isMeta || allowMeta := by grind

namespace ImportNeedsKind

@[expose] section matchers

-- We give these distinct names to avoid ambiguity.
@[match_pattern] def pubNoMeta : ImportNeedsKind :=
  { NeedsKind.pub with allowMeta := false }
@[match_pattern] def privNoMeta : ImportNeedsKind :=
  { NeedsKind.priv with allowMeta := false }
@[match_pattern] def privOfPrivNoMeta : ImportNeedsKind :=
  { NeedsKind.privOfPriv with allowMeta := false }
@[match_pattern] def metaPub : ImportNeedsKind :=
  { NeedsKind.metaPub with }
@[match_pattern] def metaPriv : ImportNeedsKind :=
  { NeedsKind.metaPriv with }
@[match_pattern] def metaPrivOfPriv : ImportNeedsKind :=
  { NeedsKind.metaPrivOfPriv with }
@[match_pattern] def pubAllowMeta : ImportNeedsKind :=
  { NeedsKind.pub with allowMeta := true }
@[match_pattern] def privAllowMeta : ImportNeedsKind :=
  { NeedsKind.priv with allowMeta := true }
@[match_pattern] def privOfPrivAllowMeta : ImportNeedsKind :=
  { NeedsKind.privOfPriv with allowMeta := true }

end matchers

instance : ToString ImportNeedsKind where
  toString k := Id.run do
    let mut tks := #[]
    if k.isExported then tks := tks.push "public"
    if k.isMeta then tks := tks.push "meta" else if k.allowMeta then tks := tks.push "(meta)"
    tks := tks.push "import"
    if k.isAll then tks := tks.push "all"
    " ".intercalate tks.toList

end ImportNeedsKind

def NeedsKind.toImportNeedsKind (k : NeedsKind) (allowMeta : Bool) :
    ImportNeedsKind :=
  { k with allowMeta := k.isMeta || allowMeta }

/-- Like `Needs`, but preserves `allowMeta`. We interpret `pub`/`priv`/`privOfPriv` from
`NeedsKind` as having `allowMeta := false`, i.e. as specifically *disallowing* a meta import.  -/
structure ImportNeeds extends toSubNeeds : Needs where
  /-- The modules which may be imported as meta or non-meta which are needed in the public scope. -/
  allowMetaPub : Bitset
  /--
  The modules which may be imported as meta or non-meta whose public scopes must be available in
  the current private scope.
  -/
  allowMetaPriv : Bitset
  /--
  The modules which may be imported as meta or non-meta whose private scopes must be available in
  the current private scope.
  -/
  allowMetaPrivOfPriv : Bitset
deriving Inhabited, BEq, Repr

namespace ImportNeeds

def empty : ImportNeeds :=
  { Needs.empty with allowMetaPub := ∅, allowMetaPriv := ∅, allowMetaPrivOfPriv := ∅ }

instance : EmptyCollection ImportNeeds := ⟨.empty⟩

-- TODO: "relaxed := false" flag that, when true, first tries to use any existing imports for
-- allowMeta
/-- Turns `ImportNeeds` into a concrete `Needs` with an opinionated choice of whether `allowMeta`
should revert to public imports (`useMeta := false`) or be regarded as meta imports
(`useMeta := true`) -/
def toNeeds (useMeta : Bool := false) (imp : ImportNeeds) : Needs where
  pub := if useMeta then imp.pub else imp.pub ∪ imp.allowMetaPub
  priv := if useMeta then imp.priv else imp.priv ∪ imp.allowMetaPriv
  privOfPriv := if useMeta then imp.privOfPriv else imp.privOfPriv ∪ imp.allowMetaPrivOfPriv
  metaPub := if !useMeta then imp.metaPub else imp.metaPub ∪ imp.allowMetaPub
  metaPriv := if !useMeta then imp.metaPriv else imp.metaPriv ∪ imp.allowMetaPriv
  metaPrivOfPriv :=
    if !useMeta then imp.metaPrivOfPriv else imp.metaPrivOfPriv ∪ imp.allowMetaPrivOfPriv

/-- Assumes that `Provides` is well-formed, i.e. is linearized and transitively closed. -/
@[inline] def isProvidedBy (n : ImportNeeds) (p : Provides) :=
  n.metaPub ⊆ p.metaPub
    && n.metaPriv ⊆ p.metaPriv
    && n.metaPrivOfPriv ⊆ p.metaPrivOfPriv
    && n.pub ⊆ p.pub && n.allowMetaPub ⊆ p.pub ∪ p.metaPub
    && n.priv ⊆ p.priv && n.allowMetaPriv ⊆ p.priv ∪ p.metaPriv
    && n.privOfPriv ⊆ p.privOfPriv && n.allowMetaPrivOfPriv ⊆ p.privOfPriv ∪ p.metaPrivOfPriv

@[inline, expose] def get (needs : ImportNeeds) (k : ImportNeedsKind) : Bitset :=
  match k with
  | .pubNoMeta => needs.pub
  | .privNoMeta => needs.priv
  | .metaPub => needs.metaPub
  | .metaPriv => needs.metaPriv
  | .privOfPrivNoMeta => needs.privOfPriv
  | .metaPrivOfPriv => needs.metaPrivOfPriv
  | .pubAllowMeta => needs.allowMetaPub
  | .privAllowMeta => needs.allowMetaPriv
  | .privOfPrivAllowMeta => needs.allowMetaPrivOfPriv

@[inline, expose] def has (needs : ImportNeeds) (k : ImportNeedsKind) (i : ModuleIdx) :
    Bool :=
  needs.get k |>.has i

@[inline, expose] def set (needs : ImportNeeds) (k : ImportNeedsKind) (s : Bitset) :
    ImportNeeds :=
  match k with
  | .pubNoMeta   => { needs with pub := s }
  | .privNoMeta  => { needs with priv := s }
  | .metaPub => { needs with metaPub := s }
  | .metaPriv => { needs with metaPriv := s }
  | .privOfPrivNoMeta => { needs with privOfPriv := s }
  | .metaPrivOfPriv => { needs with metaPrivOfPriv := s }
  | .pubAllowMeta => { needs with allowMetaPub := s }
  | .privAllowMeta => { needs with allowMetaPriv := s }
  | .privOfPrivAllowMeta => { needs with allowMetaPrivOfPriv := s }

-- TODO: check if this successfully ekes out a little extra performance by having an explicit match
@[specialize] def modify (needs : ImportNeeds) (k : ImportNeedsKind) (f : Bitset → Bitset) :
    ImportNeeds :=
  match k with
  | .pubNoMeta   => { needs with pub := f needs.pub }
  | .privNoMeta  => { needs with priv := f needs.priv }
  | .metaPub => { needs with metaPub := f needs.metaPub }
  | .metaPriv => { needs with metaPriv := f needs.metaPriv }
  | .privOfPrivNoMeta => { needs with privOfPriv := f needs.privOfPriv }
  | .metaPrivOfPriv => { needs with metaPrivOfPriv := f needs.metaPrivOfPriv }
  | .pubAllowMeta => { needs with allowMetaPub := f needs.allowMetaPub }
  | .privAllowMeta => { needs with allowMetaPriv := f needs.allowMetaPriv }
  | .privOfPrivAllowMeta => { needs with allowMetaPrivOfPriv := f needs.allowMetaPrivOfPriv }

def union (needs : ImportNeeds) (k : ImportNeedsKind) (s : Bitset) : ImportNeeds :=
  needs.modify k (· ∪ s)

end ImportNeeds

local instance : Ord Name := ⟨Name.quickCmp⟩

/-- Information about the source of a compile-time dependency. -/
inductive ComptimeDependency where
| /-- A potential compile-time dependency due to an indirect mod use.
  `imposingModule` records the module that imposed the indirect mod use (not the source module of
  the declaration). -/
  indirect (use : IndirectModUse) (imposingModules : Array Name)
| /-- A compile-time dependency due to parsing. -/
  stx (kind : SyntaxNodeKind) (pos? : Option Syntax.Range) -- TODO: just record syntax?
deriving Inhabited, BEq, Repr, Hashable, Ord

/-- A location at which a `ConstantInfo` can reference another. -/
inductive ConstLocation where | type | value
deriving Inhabited, BEq, Repr, Hashable, Ord

instance : ToString ConstLocation where
  toString | .type => "type" | .value => "value"

/-- A way in which a declaration `tgt` might need another declaration `src`. In general, the same
`src` and `tgt` may be related by multiple `DeclDeclNeedsKind`s. -/
inductive DeclDeclNeedsKind where
| /-- Expresses a dependency of `tgt`'s location given by `downstream` on `src`'s location given by
  `upstream`. `isReExported := none` indicates that the exported value is inherited from `tgt`'s
  `isPublic` or `isExposed` stance, as appropriate. (Occasionally this will be `some false` if, for
  example, a proof is abstracted, since we count the dependencies of autogenerated declarations as
  part of the parent declaration.) -/
  expr (downstream : ConstLocation) (isReExported : Option Bool := none)
    (upstream : ConstLocation := .type)
| /-- Expresses a dependency of `tgt` on `src` due to the IR of `tgt`, which is meta-available. When
  `isReExported := none`, this is inherited from the `tgt`'s `isPublic` stance (the same as its
  type, not its value.)

  Meta IR is unusual in that while a private meta def may not re-export its references, a public
  meta def that uses that private meta def will re-export that private meta def's references. Note,
  also, that this dependency is determined by Lean from the initial LCNF (unless a same-module
  transitive dependency, in which case it is determined from that declaration's base LCNF), but is
  intended to capture IR dependency. -/
  metaIR (isReExported : Option Bool := none) (through : List Name := [])
| /-- Expresses a dependency of `tgt` on `src` in the IR of `tgt`, which is only available at
  runtime. This does not have the complicated reference semantics of IR used for meta declarations.
  We assume, for now, that we do not need to think about changing runtime defs to meta defs, and
  thus do not need to record the same information. As such, `checkMeta`s recursive check for
  non-aux decls is irrelevant, as the runtime IR constraints such a recursive check puts on a
  reference are redundant with the runtime IR constraints that already exist on that reference.
  However, note that, like meta declarations, this dependency is determined by Lean from the
  initial LCNF, though is intended to capture IR dependency. -/
  runtimeIR
| /--
  A compile-time dependency of `tgt` (e.g. a parser used for notation in the command for  `tgt`).

  If this arises due to an indirect mod use, we record the declaration that demanded it (if we
  can). Note that shake extensions do not expose this; this is known during the expression
  traversal. So some indirect mod uses will end up in `extraModUses` without any indication as to
  the declaration that drew them (at least, not in a way that's accessible to us, though this
  information is traced by shake).

  We record this separately mainly for reporting.
  -/
  comptime (source : ComptimeDependency)
-- TODO: demands due to inlining/`isTransparent`. This may change soon, hence is not modeled.
-- | lcnf (isReExported : Option Bool := none)
deriving Inhabited, BEq, Repr, Hashable, Ord

namespace DeclDeclNeedsKind

/-- An English-language description of a `DeclDeclNeedsKind`. -/
def pretty : DeclDeclNeedsKind → String
  | .expr down reExported up => s!"uses {up} in {down}{
    match reExported with
    | some true => " (public)"
    | some false => " (private)"
    | none => ""}"
  | .runtimeIR => "used in runtime IR"
  | .metaIR _ _ => "used in meta IR" -- TODO
  | .comptime _ => "comptime dependency" -- TODO

/-- `some .comptime` if this demands the source declaration's `IRPhases` includes `.comptime`;
`some .runtime` if this demands the source declaration's `IRPhases` includes `.runtime`. (`.all`
includes both.) `none` if there is no demand either way (as is the case for expressions). -/
@[inline] protected def irPhaseNeeds? : DeclDeclNeedsKind → Option IRPhases
  | .expr .. => none
  | .metaIR .. | .comptime .. => some .comptime
  | .runtimeIR => some .runtime

end DeclDeclNeedsKind

/-- The intrinsic information that determines subsequent placement under different manners of
import. -/
structure Stance where
  /-- Whether the declaration is public or not. We assume we are only discussing declarations that
  appear in the environment. (If we want to relax this in the future, this might become
  `Option Bool`.) -/
  isPublic : Bool
  /-- Whether the declaration is exposed. `none` if the notion of exposure does not apply (e.g. a
  theorem). -/
  isExposed : Option Bool
  /-- Only public declarations can be exposed. -/
  isPublic_if_isExposed : (isExposed != some true) || isPublic := by
    grind [Stance.isPublic, Stance.isExposed]
  /-- Whether the declaration is meta, i.e. has exported IR. `none` if there is no IR to be
  exported. If `some false`, the declaration has runtime IR. -/
  isMeta : Option Bool
  -- TODO: needs surrounding this may change soon, so we don't model it.
  -- /-- Whether the declaration is transparent, i.e. whether its LCNF body is available. Currently
  -- we only care about the base phase of LCNF. (This may not be fully general.) `none` if there is
  -- no code this applies to. -/
  -- isTransparent : Option Bool
  /-- A flag indicating whether this is the exact stance (determined within the same module) or a
  lower bound. -/
  isExact := true

/-- Whether a `Stance` is not `isPublic`. -/
@[expose, macro_inline, grind] public def Stance.isPrivate (s : Stance) := !s.isPublic

/-- A set of declaration needs. -/
/- TODO: make this more efficient, ideally a tiny `BitsetOf`, if such API were created. Also
consider just a small `List` or `Array` that avoids duplication at insertion time. -/
abbrev DeclDeclNeedsKindSet := Std.TreeSet DeclDeclNeedsKind

/-- The demands of a single declaration, organized to facilitate movement. Free declarations are
those whose modules may change; fixed ones must remain in the same module. -/
structure DeclNeed where
  /-- Declarations whose location may be altered. -/
  freeDecls : NameMap DeclDeclNeedsKindSet := {}
  -- TODO: more efficient data structure?
  /-- Declarations whose location may not be altered. A map
  `[module name] ↦ [needs of declarations from that module]`. -/
  fixedDecls : Std.TreeMap Name (NameMap DeclDeclNeedsKindSet) := {}
  /--
  Extra module uses recorded in shake extensions during the command. Note that if several
  declarations were created during the command, the extra mod uses are the same among all of them.
  -/
  -- TODO: more performant implementation
  extraModUses : NameMap (Std.TreeSet NeedsKind) := {}
  /-- The parent declaration, if the ambient declaration is autogenerated. -/
  parentDecls : List Name := []
  /-- Any autogenerated declarations used by this declaration. -/
  childDecls : List Name := []
deriving Inhabited, Repr

/-- Records that the ambient declaration needs the declaration `decl` at availability `k`, where
the module of `decl` is left free. -/
@[inline] def DeclNeed.insertFreeDecl (k : DeclDeclNeedsKind) (decl : Name) (declNeed : DeclNeed) :
    DeclNeed :=
  { declNeed with freeDecls := declNeed.freeDecls.alter decl fun
    set? => set?.getD {} |>.insert k }

/-- Records that the ambient declaration needs the imported declaration `decl` from module `i` at
availability `k`, where `decl` is expected to stay in `i`. -/
def DeclNeed.insertFixedDecl (k : DeclDeclNeedsKind) (mod : Name) (decl : Name)
    (declNeed : DeclNeed) : DeclNeed :=
  { declNeed with
    fixedDecls := declNeed.fixedDecls.alter mod fun map? =>
      some <| map?.getD {} |>.alter decl fun set? =>
        set?.getD {} |>.insert k }

def DeclNeed.insertExtraModUses (extraModUses : List ExtraModUse) (declNeed : DeclNeed) :
    DeclNeed :=
  { declNeed with
    extraModUses :=
      extraModUses.foldl (init := declNeed.extraModUses) fun extraModUseMap extraModUse =>
        extraModUseMap.alter extraModUse.module fun ks? =>
          ks?.getD {} |>.insert { extraModUse with } }

@[inline] def DeclNeed.isAutoDecl (declNeed : DeclNeed) : Bool :=
  !declNeed.parentDecls.isEmpty

/-- A collection of needs per declaration. -/
-- TODO: more efficient data structure
abbrev DeclNeeds := NameMap DeclNeed

@[inline] def DeclNeeds.insertAutoDeclLink (autoDecl parentDecl : Name) (declNeeds : DeclNeeds) :
    DeclNeeds :=
  declNeeds.alter autoDecl (fun need? =>
      let need := need?.getD {}
      some { need with parentDecls := parentDecl :: need.parentDecls })
    |>.alter parentDecl fun need? =>
      let need := need?.getD {}
      some { need with childDecls := autoDecl :: need.childDecls }

@[inline] def DeclNeeds.insertFreeDeclFor (currentDecl : Name) (k : DeclDeclNeedsKind)
    (usedDecl : Name) (declNeeds : DeclNeeds) : DeclNeeds :=
  declNeeds.alter currentDecl fun need? => need?.getD {} |>.insertFreeDecl k usedDecl

@[inline] def DeclNeeds.insertFixedDeclFor (currentDecl : Name) (k : DeclDeclNeedsKind)
    (mod : Name) (usedDecl : Name) (declNeeds : DeclNeeds) :
    DeclNeeds :=
  declNeeds.alter currentDecl fun need? => need?.getD {} |>.insertFixedDecl k mod usedDecl

@[inline] def DeclNeeds.insertExtraModUsesFor (decl : Name) (extraModUses : List ExtraModUse)
    (declNeeds : DeclNeeds) : DeclNeeds :=
  declNeeds.alter decl fun need? => need?.getD {} |>.insertExtraModUses extraModUses

/-- Returns `false` if `s.isExposed = none`. Because of that, this is **not** necessarily equivalent
to `!(s.isPrivateAt loc)`. -/
def Stance.isPublicAt (s : Stance) : ConstLocation → Bool
  | .type  => s.isPublic
  | .value => s.isExposed.getD false

/-- Returns `false` if `s.isExposed = none`. Because of that, this is **not** necessarily equivalent
to `!(s.isPublicAt loc)`. -/
def Stance.isPrivateAt (s : Stance) : ConstLocation → Bool
  | .type  => !s.isPublic
  | .value => !(s.isExposed.getD true)

/-- Finds the stance of the given declaration, assuming `decl` is not imported. Returns `none` if
`decl` is either not in the environment or is imported. -/
def findStanceOfNonImported? (decl : Name) : CoreM (Option Stance) :=
  withoutExporting do
  let env ← getEnv
  if env.isImportedConst decl || !env.contains decl then return none
  -- From `calcNeeds`:
  -- Added guard for cases like `structure` that are still exported even if private
  let pubCI? := guard (!isPrivateName decl) *> (env.setExporting true).find? decl
  let isPublic := pubCI?.isSome
  let isExposed := pubCI?.bind fun ci => if ci.isDefinition then ci.hasValue else none
  -- TODO: Are we handling implemented_by, matcher inlining, and macro_inline correctly?
  let isMeta :=
    if ← pure !(isNoncomputable env decl) <&&> Compiler.LCNF.shouldGenerateCode decl then
      some (isMarkedMeta env decl) else none
  return some { isPublic, isExposed, isMeta, isPublic_if_isExposed := by grind [Option] }

open Compiler in
/-- Like `shouldGenerateCode`, but for imported constants. -/
def shouldHaveGeneratedCode (declName : Name) : CoreM Bool := do
  if (← isCompIrrelevant |>.run') then return false
  let env ← getEnv
  if isExtern env declName then return true
  -- This is the only different part of the code.
  -- Infers what the outcome of the check for a value would have been.
  let some kind := getOriginalConstKind? env declName | return false
  unless kind == .defn || kind == .opaque do return false
  if hasMacroInlineAttribute env declName then return false
  if (getImplementedBy? env declName).isSome then return false
  if (← Meta.isMatcher declName) then return false
  if (← Meta.isMatcherLike declName) then return false
  if isCasesOnLike env declName then return false
  -- TODO: check if type class instance
  return true
where
  isCompIrrelevant : MetaM Bool := do
    let info ← getConstInfo declName
    Meta.isProp info.type <||> Meta.isTypeFormerType info.type

/-- Approximates the stance of the imported declaration `decl` by a "lower bound". This means that
we assume that any "extra information" is due to provisioning rather than the stance. For example,
an `import all` will provide the body of every definition regardless of whether it is exposed or
not. We therefore assume it is *not* exposed and that `import all` is doing the work. This allows
us to ensure we have the imports we need. In most cases, however, this lower bound is sharp and
matches the actual stance. -/
-- TODO: record when a stance is approximated.
def findLowerBoundStanceOfImported? (decl : Name) : CoreM (Option Stance) :=
  withoutExporting do
  let env ← getEnv
  let some idx := env.getModuleIdxFor? decl | return none
  let mod := env.header.modules[idx]!
  unless mod.hasData do return none
  unless env.contains decl do return none -- exclude compiler defs as well
  let isMeta :=
    -- TODO: use `isDeclMeta'` or not?
    if ← pure !(isNoncomputable env decl) <&&> shouldHaveGeneratedCode decl then
      some (isMarkedMeta env decl) else none
  if !mod.importAll then
    letI isPublic := true -- It must be public if we can see it
    -- Look in the private scope as well in case it's imported privately
    -- (This is why `hasExposedBody` is wrong downstream)
    -- This is redundant given the outer `withExporting`, but for readability.
    let isExposed := (env.setExporting false).find? decl |>.any (·.hasValue)
    return some {
      isPublic, isExposed, isMeta, isPublic_if_isExposed := by grind [Option]
      isExact := true }
  else
    -- We demand a public name to be considered public.
    -- If publicly imported, exposure is determined by whether it has a value.
    -- If privately imported, we assume that exposure is the `import all`'s doing.
    let ci? := guard (!isPrivateName decl) *>
      (((env.setExporting true).find? decl).map (·.hasValue)
        <|> ((env.setExporting false).find? decl).map fun _ => false)
    let isPublic := ci?.isSome
    let kind? := getOriginalConstKind? env decl
    let isExposable := kind?.isEqSome .defn || kind?.isEqSome .opaque
    let isExposed := if isExposable then ci? else none
    return some {
      isPublic, isExposed, isMeta, isPublic_if_isExposed := by grind [Option]
      isExact := false }

/-- The `ImportNeedsKind` implied by a downstream constant with stance `downstreamStance` demanding
a declaration with stance `upstreamStance` via `demand : DeclDeclNeedsKind`. Assumes that the
demand is satisfiable by the upstream declaration (e.g. that we are not trying to use an
intrinsically private declaration in a public position).

Note that this does not account for indirect module uses. -/
def Stance.toImportNeedsKind
    (downstreamStance : Stance) (demand : DeclDeclNeedsKind) (upstreamStance : Stance) :
    -- TODO: optional argument `(allowExprPhaseMixing := true)`
    ImportNeedsKind :=
  match demand with
  | .expr downstreamLoc isReExported upstreamLoc =>
    let isExported := isReExported.getD <| downstreamStance.isPublicAt downstreamLoc
    { isExported
      isAll := !isExported && upstreamStance.isPrivateAt upstreamLoc
      isMeta := false, allowMeta := true }
  | .runtimeIR =>
    { isExported := false
      isAll := upstreamStance.isPrivate
      isMeta := false, allowMeta := false } -- Note: can't mix phases, hence `allowMeta := false`
  | .metaIR isReExported _ =>
    let isExported := isReExported.getD <| downstreamStance.isPublic
    -- Meta upstream definitions do not need to be imported as meta.
    -- If all is well, we never hit the `none` case.
    let isMeta := !(upstreamStance.isMeta.getD false)
    { isExported
      isAll := !isExported && upstreamStance.isPrivate
      isMeta, allowMeta := true }
  | .comptime _ =>
    -- We could assume all code that ends up recording a compile time usage is intrinsically meta,
    -- but we don't just in case. If all is well, we never hit the `none` case.
    let isMeta := !(upstreamStance.isMeta.getD false)
    { isExported := false -- There is no re-export demand on compile-time code.
      isAll := upstreamStance.isPrivate
      isMeta, allowMeta := true }

-- TODO: make this monad-generic instead of just `CoreM`.
/-- `CoreM` together with a cache for `Stance`s. -/
abbrev StanceM := MonadCacheT Name (Option Stance) CoreM

nonrec abbrev StanceM.run {α} (x : StanceM α) (s : Std.HashMap Name (Option Stance) := ∅) :
    CoreM (α × Std.HashMap Name (Option Stance)) :=
  StateRefT'.run x s
nonrec abbrev StanceM.run' {α} (x : StanceM α) (s : Std.HashMap Name (Option Stance) := ∅) :
    CoreM α := x.run' s

/-- Gets the stance of the given declaration. Records `none` if no stance could be found. This is
insensitive to the `isExporting` flag on the ambient environment. -/
def getStance? (decl : Name) : StanceM (Option Stance) := do
  checkCache decl fun _ => do
    if let some stance ← findStanceOfNonImported? decl then
      trace[ImportGraph.Shake] "Found local stance for `{.ofConstName decl}`"
      return stance
    else if let some stance ← findLowerBoundStanceOfImported? decl then
      trace[ImportGraph.Shake] "Found upstream stance for `{.ofConstName decl}`"
      return stance
    else
      trace[ImportGraph.Shake] "Could not find stance for `{.ofConstName decl}`"
      return none

/-- An approximation to whether something is an autogenerated declaration whose base decl is its
prefix. This should be improved. -/
@[inline] def isDeclNeedsAutoDecl (env : Environment) (c : Name) :=
  c.isStr && c.getString!.startsWith '_'
    && ((env.setExporting false).contains c.getPrefix ||
      (isPrivateName c && (env.setExporting false).contains (privateToUserName c.getPrefix)))
    && !(env.isImportedConst c)
    -- Autogenerated declarations usually lack declaration ranges.
    && (declRangeExt.find? (level := .exported) env c <|>
      declRangeExt.find? (level := .server) env c).isNone

/-- Calculate the needs of the given declaration based on its `ConstInfo` (type and value). -/
partial def calcDeclConstInfoNeeds (decl : Name) (env : Environment)
    (currentDecls : DeclNeeds := {}) (isReExported : Option Bool := none) : DeclNeeds := Id.run do
  if env.isImportedConst decl || currentDecls.contains decl then return currentDecls
  let mut declNeeds : DeclNeeds := currentDecls.insert decl {}
  -- TODO: should we be getting the reason, and do our own custom import? Maybe.
  -- We could also look up the reason later.
  let some ci := (env.setExporting false).find? decl | return declNeeds
  let indirectModUses := indirectModUseExt.getState env
  declNeeds := visitExpr indirectModUses .type isReExported ci.type declNeeds
  if let some e := ci.value? (allowOpaque := true) then
    declNeeds := visitExpr indirectModUses .value isReExported e declNeeds
  return declNeeds
where
  /-- Accumulate the results from expression `e` into `deps`. -/
  visitExpr
      (indirectModUses : Std.HashMap Name (Array ModuleIdx)) (loc : ConstLocation)
      (isReExported : Option Bool) (e : Expr) (declNeeds : DeclNeeds) : DeclNeeds :=
    e.foldConsts declNeeds fun c declNeeds => Id.run do
      let mut declNeeds := declNeeds
      -- Hope that reserved names register appropriate extra mod uses.
      -- SQ: is that true?
      let some c := env.getDepConstName? c | return declNeeds
      if let some j := env.getModuleIdxFor? c then
        -- TODO: what about imported autogenerated declarations?
        let modName := env.header.modules[j]!.module
        declNeeds := declNeeds.insertFixedDeclFor decl (.expr loc isReExported) modName c
        if let some indMods := indirectModUses[c]? then
          let indMods := indMods.map (env.header.modules[·]!.module)
          declNeeds := declNeeds.insertFixedDeclFor decl
            -- TODO: don't have the `IndirectModUse`s per se :/
            (.comptime <| .indirect { kind := "calcDeclConstInfoNeeds", declName := c } indMods)
            modName c
        return declNeeds
      else
        if isDeclNeedsAutoDecl env c then
          -- Insert regardless of whether this autodecl comes from *this* declaration, since
          -- sometimes autodecls are reused due to caching.
          declNeeds := declNeeds.insertAutoDeclLink c decl
        if (env.setExporting false).contains c && !(c == decl) then
          declNeeds := declNeeds.insertFreeDeclFor decl (.expr loc isReExported) c
          calcDeclConstInfoNeeds c env declNeeds isReExported
        else
          return declNeeds

open Lean Elab Command in
/-- Calcualte the syntax needs of some syntax, and attaches it as a comptime need for all `decls`.
This design will likely change in the future, and command needs will have a dedicated location
instead of being duplicated across different declarations. -/
def DeclNeeds.calcSyntaxNeeds (env : Environment) (decls : Array Name) (cmd : Syntax)
    (declNeeds : DeclNeeds) : CommandElabM DeclNeeds := do
  trace[ImportGraph.Shake] "Calculating syntax needs for:\
    {indentD <| toMessageData <| decls.map MessageData.ofConstName}"
  let indirectModUses := indirectModUseExt.getState env
  let mut declNeeds := declNeeds
  for stx in cmd.topDown do
    if let .node _ k .. := stx then
      -- do not record builtin parsers, they do not have to be imported
      if !(← Parser.builtinSyntaxNodeKindSetRef.get).contains k then
        if let some idx := env.getModuleIdxFor? k then
          let need := .comptime <| .stx k stx.getRange?
          let modName := env.header.modules[idx]!.module
          for decl in decls do
            declNeeds := declNeeds.insertFixedDeclFor decl need modName k
            if let some indirects := indirectModUses[k]? then
              let need := .comptime <| .indirect { kind := "calcSyntaxNeeds", declName := k } <|
                indirects.map (env.header.modules[·]!.module)
              declNeeds := declNeeds.insertFixedDeclFor decl need modName k
        else if env.contains k then
          unless declNeeds.contains k do
            declNeeds := calcDeclConstInfoNeeds k env declNeeds
          let need := .comptime <| .stx k stx.getRange?
          for decl in decls do
            declNeeds := declNeeds.insertFreeDeclFor decl need k
  return declNeeds

-- TODO: interleave with expression needs? Is that ever necessary? I'd hope not.
open Compiler.LCNF in
/-- Calculates the IR needs of a declaration. Currently ignores meta IR. -/
def DeclNeeds.calcIRNeeds (declNeeds : DeclNeeds) : StanceM DeclNeeds := do
  let mut declNeeds := declNeeds
  for (decl, _) in declNeeds do
    withTraceNode `ImportGraph.Shake
      (fun _ => return m!"Calculating IR needs for {.ofConstName decl}") do←
    let some stance ← getStance? decl | continue
    if let some isMeta := stance.isMeta then
      -- TODO: handle `isMeta = some true`
      if isMeta then
        trace[ImportGraph.Shake] "Skipping meta definition (for now)"
        continue
      try
        let lcnf ← (Compiler.LCNF.toDecl decl).run
        let (_, declNeeds') ← StateT.run (s := declNeeds) <| lcnf.value.forCodeM fun code =>
          for ref in collectUsedDecls code do
            -- TODO: should we check the refstance here?
            -- SQ: Is .all lifted up into .comptime under meta import, for e.g. constructors,
            -- rendering using them unacceptable...?
            if let some modIdx := (← getEnv).getModuleIdxFor? ref then
              let modName := (← getEnv).header.modules[modIdx]!.module
              trace[ImportGraph.Shake] "uses `{.ofConstName ref}` from `{modName}`"
              modify (·.insertFixedDeclFor decl .runtimeIR modName ref)
            else if (← getEnv).contains ref then -- just in case
              trace[ImportGraph.Shake] "uses `{.ofConstName ref}` from current module"
              modify (·.insertFreeDeclFor decl .runtimeIR ref)
            -- TODO: recurse
        declNeeds := declNeeds'
      catch ex =>
        trace[ImportGraph.Shake] "`{.ofConstName ``toDecl} {.ofConstName decl}` failed:\
          {indentD ex.toMessageData}"
  return declNeeds

open Lean Elab Command in
/-- Elaborates the command and captures the `DeclNeeds` of all new declarations. Attaches the needs
implied by the command's syntax to each new declaration. Note: does **not** capture extra rev mod
uses influencing the file as a whole. -/
def withElabCommandCapturingNeeds (cmd : Syntax.Command) :
    CommandElabM (DeclNeeds × Array Name) := do
  withFreshShakeRecords do
    let oldEnv ← getEnv
    elabCommand cmd
    let env ← getEnv
    let newDecls := env.constants.foldStage2 (s := #[]) fun acc decl _ =>
      if oldEnv.contains decl then acc else acc.push decl
    let mut declNeeds := {}
    let mut autoDecls := #[] -- Save auto decls, and ensure we found them
    -- TODO-TAG: auto decl handling
    for new in newDecls do
      if isDeclNeedsAutoDecl env new then
        autoDecls := autoDecls.push new
      else
        declNeeds := calcDeclConstInfoNeeds new env declNeeds
    for autoDecl in autoDecls do
      -- TODO: this should recurse into autodecls of autodecls. Not entirely happy with handling
      unless declNeeds.contains autoDecl do
        declNeeds := calcDeclConstInfoNeeds autoDecl env declNeeds
    -- TODO: extra mod uses. Should be at the command level and decls organized by command
    let extraModUses := getNewExtraModUses env |>.1
    for new in newDecls do
      declNeeds := declNeeds.insertExtraModUsesFor new extraModUses
    declNeeds ← declNeeds.calcSyntaxNeeds env newDecls cmd
    declNeeds ← liftCoreM <| declNeeds.calcIRNeeds.run'
    return (declNeeds, newDecls)
