/-
Copyright (c) 2026 Thomas R. Murrills. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison, Paul Lezeau, Thomas R. Murrills
-/
module

public meta import Lean.Widget.UserWidget

/-! # Go-To-Module utilies

This file defines:

- `goToModule`, a clickable widget bringing the user to a given module (at a customizable
  position and with customizable visible text)
- `goToModuleOfDecls`/`goToModuleOfDecl`, the same for bringing the user to the position before or
  after declarations from a (single) module, as specified
-/

open Lean

public meta section

namespace ImportGraph.Widget

open Server in
/-- Tries to resolve the module `modName` to a source file URI.
This has to be done in the Lean server
since the `Environment` does not keep track of source URIs. -/
@[server_rpc_method]
public def getModuleUri (modName : Name) : RequestM (RequestTask Lsp.DocumentUri) :=
  RequestM.asTask do
    let some uri ← documentUriFromModule? modName
      | throw <| RequestError.invalidParams s!"Couldn't find URI for module `{modName}`"
    return uri

/-- Widget props for `ImportGraph.Widget.GoToModule`. -/
structure GoToModuleProps where
  modName : Name
  pos : Lsp.Position := { line := 0, character := 0 }
  overrideText : Option String := none
deriving Server.RpcEncodable

/-- When clicked, this widget component jumps to the source of the module `modName` at the provided `pos`, assuming a source URI can be found for the module. Allows `override -/
@[widget_module]
def GoToModule : Widget.Module where javascript := r#"
import * as React from 'react'
import { EditorContext, useRpcSession } from '@leanprover/infoview'

export default function(props) {
  const ec = React.useContext(EditorContext)
  const rs = useRpcSession()
  return React.createElement('a',
    {
      className: 'link pointer dim',
      onClick: async () => {
        try {
          const uri = await rs.call('ImportGraph.Widget.getModuleUri', props.modName)
          ec.revealPosition({ uri, line: props.pos.line, character: props.pos.character })
        } catch {}
      }
    },
    props.modName)
}
"#

/-- Creates a clickable link which takes the user to the provided module.

By default, takes the user to the top of the module. Providing `pos` will bring the user to that
position in the file.

By default, the module name is used as the link's text. The text can be overridden by providing
`overrideText`.
-/
def goToModule (modName : Name) (pos : Lsp.Position := ⟨0,0⟩)
    (overrideText : Option String := none) : CoreM MessageData := do
  let p : GoToModuleProps := { modName, pos, overrideText }
  return .ofWidget
    (← Widget.WidgetInstance.ofHash GoToModule.javascriptHash <|
      Server.RpcEncodable.rpcEncode p)
    -- Note that `Lsp.Position`s are 0-indexed, hence the `+1`.
    -- (However, Lean uses 0-indexed columns in messages.)
    m!"{overrideText.getD <| toString modName} ({pos.line + 1}:{pos.character})"

/-- A position past the end of any file, assuming no file has more than 4294967296 lines. -/
def pastEndOfFile : Lsp.Position := { line := 1 <<< 32, character := 0 }

/-- Gets the latest-ending range among all declarations, or `none` if none could be found.
Assumes all declarations come from the same module. -/
def getMaxDeclarationRange? (decls : Array Name) : CoreM (Option DeclarationRange) := do
  let mut maxRange? := none
  for decl in decls do
    -- TODO: different behavior if we can't find the range? e.g. consider base name of
    -- autogenerated decls
    let some { range .. } ← findDeclarationRanges? decl | continue
    if let some maxPos := maxRange? then
      if maxPos.endCharUtf16 < range.endCharUtf16 then
        maxRange? := range
    else
      maxRange? := range
  return maxRange?

/-- Gets the earliest-starting range among all declarations, or `none` if none could be found.
Assumes all declarations come from the same module. -/
def getMinDeclarationRange? (decls : Array Name) : CoreM (Option DeclarationRange) := do
  let mut minRange? := none
  for decl in decls do
    -- TODO: different behavior if we can't find the range? e.g. consider base name of
    -- autogenerated decls
    let some { range .. } ← findDeclarationRanges? decl | continue
    if let some minPos := minRange? then
      if range.charUtf16 < minPos.charUtf16 then
        minRange? := range
    else
      minRange? := range
  return minRange?

/-- Where the cursor should end up relative to given range(s) after a go-to-module. -/
inductive RelativeRangeLocation where
| /-- Places the cursor by default on the line before the range(s).
  If `lineBefore := false`, places the cursor just at the start of the range(s). -/
  start (lineBefore := true)
| /-- Places the cursor by default on the line after the range(s).
  If `lineAfter := false`, places the cursor just at the end of the range(s). -/
  end (lineAfter := true)

/--
Goes to either before or after all of the ranges of all provided `decls`. The location the cursor
ends up may be specified by setting `location`:

- `.end (lineAfter := true)` (the default): go the first character of the line after the range of
  the last declaration.
- `.end (lineAfter := false)`: place the cursor at the end of the range of the last declaration.
- `.start (lineBefore := true)`: place the cursor on the line before the first declaration.
- `.start (lineBefore := false)`: place the cursor at the beginning of the range of the first
  declaration.

(We use the full range, including e.g. the body of the declaration.)

Errors if no `decl` has a module and `fallBackModule` is not specified.

Ignores declarations with no position information (such as autogenerated declarations). If a module
is found but no range can be found, goes to the end or beginning of the module, according to
`location`.

Errors if not all declarations come from the same module.

By default, the link text is the name of `decl`'s module. The text can be overridden with
`overrideText`.
-/
def goToModuleOfDecls (decls : Array Name) (location := RelativeRangeLocation.end)
    (fallbackModule : Option Name := none) (overrideText : Option String := none) :
    CoreM MessageData := do
  let env ← getEnv
  let some moduleIdx := decls.firstM env.getModuleIdxFor? <|> fallbackModule.bind env.getModuleIdx?
    | throwError "Could not find module when constructing go-to-module link."
  unless decls.all fun decl => (env.getModuleIdxFor? decl).all (· == moduleIdx) do
    throwError "Not all provided declarations come from the same module."
  let pos ← match location with
    | .end lineAfter => do
      let some range ← getMaxDeclarationRange? decls | pure pastEndOfFile
      let pos := range.toLspRange.end
      if lineAfter then pure { line := pos.line + 1, character := 0 } else pure pos
    | .start lineBefore => do
      let some range ← getMinDeclarationRange? decls | pure { line := 0, character := 0 }
      let pos := range.toLspRange.start
      if lineBefore then pure { line := pos.line - 1, character := 0 } else pure pos
  let mod := env.header.modules[moduleIdx]!.module
  goToModule mod pos overrideText

/--
Goes to either before or after the range of the provided `decl`. The location the cursor
ends up may be specified by setting `location`:

- `.end (lineAfter := true)` (the default): go the first character of the line of the declaration.
- `.end (lineAfter := false)`: place the cursor at the end of the range of the declaration.
- `.start (lineBefore := true)`: place the cursor on the line before the declaration.
- `.start (lineBefore := false)`: place the cursor at the beginning of the range of the declaration.

(We use the full range, including e.g. the body of the declaration.)

Errors if `decl` has no module.

If the declaration has a module but no range can be found, goes to the end or beginning of the
module, according to `location`.

Errors if not all declarations come from the same module.

By default, the link text is the name of `decl`'s module. The text can be overridden with
`overrideText`.
-/
@[inline] def goToModuleOfDecl (decl : Name) (location := RelativeRangeLocation.end)
    (overrideText : Option String := none) : CoreM MessageData := do
  goToModuleOfDecls #[decl] location (overrideText := overrideText)
